### ISSUE TITLE
Add color and other customization options

### ISSUE THREAD

**Issue by fdrake97** [VATSIM-Radar/vatsim-radar#107]
### Your Vatsim CID

1664386

### What do you suggest?

Add many customization options, for example:
- colors and opacity for all different atc positions, sectors, aircraft, etc.
- airplane icon size
- font sizes
- info to be displayed on the map, for example non-staffed major airports

### Why do you need that?

This would allow each individual user to customize the experience completely to their liking, which would help to make Vatsim Radar the best user experience/interface app for vatsim tracking.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
I'll at least try to do it for 0.5.0
