### ISSUE TITLE
Aircraft location heatmap

### ISSUE THREAD

**Issue by fdrake97** [VATSIM-Radar/vatsim-radar#108]
### Your Vatsim CID

1664386

### What do you suggest?

Implement a sort of "heatmap" option that shows locations where many users are densely populated. Amusingly, a current glitch in SimAware shows a rudimentary version of this exact feature.
![image](https://github.com/daniluk4000/vatsim-radar/assets/87662019/d4f05074-bf3f-4da4-a05d-055e9de15ef0)

### Why do you need that?

Currently, in all vatsim trackers it is difficult to tell which airports are more heavily populated without zooming into individual airports to check the amount of traffic. Having a heatmap that shows the locations where more aircraft are located would allow users to easily find airports with traffic, and choose flights between particular airports. SimAware has a top-10 most popular airports list, but it doesn't help much with choosing where to fly because it doesn't show how close together popular airports are. In the attached screenshot, someone could look at the heatmap and choose their flight based on how long they want it to be. For example if they want to do a ~1 hour flight with some traffic, they can see that SFO-SAN, JFK-DCA, DCA-ATL are all good options, for a ~2-3 hour flight they could see ORD-JFK, ORD-CLT, and so on. A top-10 list just doesn't help as much for planning a traffic-filled flight.

### Additional info

 This could be very easily accomplished by making a map layer where aircraft icons are shown as almost completely transparent, very wide discs rather than actual airplanes. If each aircraft's disc adds onto the other aircrafts, we will have a heatmap where the brighter parts of the map are more densely packed with traffic.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by RoboFun01** [comment]
I think it would be very cool and nice to add, but for me it would definitely be nice if it was a type of map layer, so that I can toggle between the normal view, as it is now, and the heatmap. 😀

**Comment by fdrake97** [comment]
> I think it would be very cool and nice to add, but for me it would definitely be nice if it was a type of map layer, so that I can toggle between the normal view, as it is now, and the heatmap. 😀

Oh absolutely! Separate from the normal map for sure.
