### ISSUE TITLE
Can't zoom when the coursor is on the icon of ATC 

### ISSUE THREAD

**Issue by Tushka134** [VATSIM-Radar/vatsim-radar#138]
### Your Vatsim CID

1359973

### Radar version

v0.4.2-alpha.3

### Describe your issue

When you point your mouse on the icon of the ATC you can't zoom in/zoom out. 
May be it is not a bug but kinda... annoying as for me 

https://github.com/daniluk4000/vatsim-radar/assets/173595392/6a856a56-c997-4b7d-90b6-37dac645aeab

### Reproduction steps

1.Place your mouse on icon of the ATC
2. Try to zoom using your mouse wheel

### Platform

Win 10

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
Production issue. Changed this to enhancement. It IS a feature due to scroll, but it can be improved.
