### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by Foamyexe** [VATSIM-Radar/vatsim-radar#141]
### Your Vatsim CID

1545793

### What do you suggest?

It would be cool to have a search bar like in simaware, on that search bar you can put callsigns and airports, it would say the details as you have clicked on the aircraft/airport

### Why do you need that?

It can be helpful to find friends, check airports info instead of trying to find it on the map, it can even be to check who is using our callsign in case its still in use

### Additional info

If you need any help of how it would work feel free to contact me via discord :)

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by DotWallop** [comment]
Feature already planned for stage 3 in the roadmap:
https://vatsim-radar.com/roadmap
