### ISSUE TITLE
How airport stats are displayed on the map

### ISSUE THREAD

**Issue by glott** [VATSIM-Radar/vatsim-radar#150]
### Your Vatsim CID

redacted

### What do you suggest?

Rather than displaying on-ground departures, on-ground arrivals, and prefiles; display on-ground departures, **all** arrivals with speed > 0, and prefiles. This gives a better picture about how busy the airport currently is and how busy it is expected to be. 

I would personally be in favor of showing all departures versus just on-ground, but that information is less useful. 

By displaying all arrivals with speed > 0, it shows that an airport is actually expecting traffic (rather than the current situation which just indicates a plane recently landed, which is not useful)

### Why do you need that?

Currently, vatsim-radar shows departures/arrivals only if that aircraft is on the ground (as well as prefiles). At a quick glance, it’s hard to determine how busy it is at an airport or how busy it will be, especially for airports with no traffic on the ground. 

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by glott** [comment]
This is similar to https://github.com/daniluk4000/vatsim-radar/issues/117#issue-2380785772 but possibly handles the solution in a different way.

**Comment by DotWallop** [comment]
This would be a very good enhancement indeed! Much more defined and descriptive.

**Comment by daniluk4000** [comment]
I'll try to solve things in 0.5.0 as setting
