### ISSUE TITLE
Map "shaking"

### ISSUE THREAD

**Issue by Tushka134** [VATSIM-Radar/vatsim-radar#157]
### Your Vatsim CID

1359973

### Radar version

 v0.4.2

### Describe your issue

When you open the website the map starts to "shake"

https://github.com/daniluk4000/vatsim-radar/assets/173595392/19e31df1-599a-45e3-8562-ce4b80b92d55

https://github.com/daniluk4000/vatsim-radar/assets/173595392/9616968e-0cf2-40c6-af74-b294be932d59

### Reproduction steps

honestly, I don't know. I just opened the website and this issue occured

### Platform

Win 10

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
That's because you are close to the edge. Will think of possible fixes
