### ISSUE TITLE
Kodiak 100 icon

### ISSUE THREAD

**Issue by m-9c** [VATSIM-Radar/vatsim-radar#161]
### Your Vatsim CID

974571

### What aircraft icon(s) do you suggest to add

Kodiak 100 - K100

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by m-9c** [comment]
Hi @daniluk4000 ,

![image](https://github.com/user-attachments/assets/5e606ab7-052f-4002-9ecb-3e3f81867ad0)

I'm still seeing the default icon for the Kodiak.

I've confirmed I'm using the correct ICAO code - K100.

![image](https://github.com/user-attachments/assets/7dc8c069-cead-43cc-8cff-5a9efa37f58f)

**Comment by daniluk4000** [comment]
Affirmative, sir. This is not on production yet.

**Comment by m-9c** [comment]
No problems, sorry for the confusion. I had thought it was in the beta release. :)
