### ISSUE TITLE
Show airport ICAO code above the aicraft icons when no ATC is online

### ISSUE THREAD

**Issue by FX5F** [VATSIM-Radar/vatsim-radar#164]
### Your Vatsim CID

-

### What do you suggest?

If there is ATC at an airport, the airport overlay is shown above the aircraft icons:
![grafik](https://github.com/daniluk4000/vatsim-radar/assets/77800397/0e86a979-413b-4dae-9a0e-06f125ea4a4e)

But if there is no ATC online, the airport icao overlay is shown below the aircraft icons:
![grafik](https://github.com/daniluk4000/vatsim-radar/assets/77800397/f052de22-17d7-4dbd-a16c-1d6dff0cbe9e)

I think it would be more useful if the airport icao is also shown above the aircraft icons when there is no ATC.

### Why do you need that?

Better visualisation.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by glott** [comment]
Nice complement to https://github.com/daniluk4000/vatsim-radar/issues/132
