### ISSUE TITLE
Hovering in general still a little buggy, not immediately responsive enough

### ISSUE THREAD

**Issue by fdrake97** [VATSIM-Radar/vatsim-radar#171]
### Your Vatsim CID

1664386

### Radar version

0.4.2

### Describe your issue

Hovering over aircraft/ATC is still not quite 100% working, there are cases where you move your mouse over something but nothing happens.

https://github.com/user-attachments/assets/e2818f3e-e9d8-4133-8120-a72f5b564098

https://github.com/user-attachments/assets/b4da56d9-f35c-4e87-a7e7-79d1c828061f

### Reproduction steps

Try hovering over certain aircraft or ATC.

### Platform

windows 11 chrome

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Everything you shown regarding aircrafts are features, but approach still needs more work though

**Comment by fdrake97** [comment]
Why are you not able to hover over certain aircraft?

**Comment by daniluk4000** [comment]
Missclick protection

**Comment by fdrake97** [comment]
I see, that makes sense. I feel like it's a little too aggressive then; in the more zoomed in video I sent, those two aircraft seem like they should be far apart enough to be click/hoverable

**Comment by daniluk4000** [comment]
Should be better in 0.4.4

**Comment by fdrake97** [comment]
I'm still seeing some issues with this

https://github.com/user-attachments/assets/2fe7fa64-cf23-4efa-839e-20ce3d25913c
