### ISSUE TITLE
"Frequency list" in ATC dropdown

### ISSUE THREAD

**Issue by DotWallop** [VATSIM-Radar/vatsim-radar#179]
### Your Vatsim CID

1227980

### What do you suggest?

Related to https://github.com/daniluk4000/vatsim-radar/issues/178, it would be highly beneficial as an ATC to display a list over all the aircraft currently tuned to your station. Not sure this one requires much explanation, but would have to be somewhere either in the dropdown list, or perhaps as a separate frame so you can have it open without having your own details open (which you don't really need when controlling)? 😄

Perhaps populating this list with some relevant info like destination airport for arrivals, departure airport for departures etc.

### Why do you need that?

Having an overview over who's tuned to your frequency is very beneficial in many ways, for troubleshooting, situational awareness etc.

### Alternatives

No alternative today

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by FX5F** [comment]
Sometimes stations have cross coupled multiple frequencies. So you can't rely only on the primary frequency. Not sure if the data contains the additional frequencies.**

**Comment by daniluk4000** [comment]
> Sometimes stations have cross coupled multiple frequencies. So you can't rely only on the primary frequency. Not sure if the data contains the additional frequencies.

It does not.

But anyways, this suggestion is good for both controller popup and airport dashboard as frequency input.
