### ISSUE TITLE
Airport aircraft count icons

### ISSUE THREAD

**Issue by Tushka134** [VATSIM-Radar/vatsim-radar#190]
### Your Vatsim CID

1359973

### What do you suggest?

each airport has green, red, and so on arrows, according to the type of arrival, departure, and so
on offer.
 if the pilot's departure and arrival airports coincide (i.e. he flies patterns, for example), just write the letter T in front of the airport in the same place where the arrows are, such as training flight
 
![изображение](https://github.com/user-attachments/assets/dde303b7-0dca-4cb2-b963-227d56a4ed69)

### Why do you need that?

It improves pilot's and ATC's situation awareness before connecting to the VATSIM for example.
It's very helpful in terms of training aerodromes. 

### Validation

- [x] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Ooo great idea
