### ISSUE TITLE
Transition contains incorrect information

### ISSUE THREAD

**Issue by jannikvogel** [VATSIM-Radar/vatsim-radar#191]
### Your Vatsim CID

1432304

### Radar version

0.4.2

### Describe your issue

![grafik](https://github.com/user-attachments/assets/032d92a5-6e43-4ab9-8f2f-b504677fab4a)
The transition information field contains invalid information. First of all, there is the transition **altitude**, secondly the transition **level**. Which is supposed to be displayed here? Transition altitude is A5000 ft in all of Germany, the transition level is assigned by ATC. Those two are not the same thing as it is implied by the information in the box. 

### Reproduction steps

-

### Platform

Windows, Firefox

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Incorrect display. I'll rework this!

**Comment by daniluk4000** [comment]
![image](https://github.com/user-attachments/assets/54a3bc7e-1214-4a3e-af0a-25c7b82ed905)
