### ISSUE TITLE
SCT_APP lights up SCT_DEP

### ISSUE THREAD

**Issue by zladatm** [VATSIM-Radar/vatsim-radar#216]
### Your Vatsim CID

845421

### Radar version

0.4.3

### Describe your issue

Users with the call sign "SCT_APP" are only lighting up the area associated with "LAX_DEP." Same data appears fine in SimAware. 

### Reproduction steps

Open vatsim-radar while SCT_APP is online, see that only a partial area is drawn.  See image: https://fma.ac/qEgeS

### Platform

Windows 10 Chrome

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by zladatm** [comment]
![chrome_Wxlq0kOi2V](https://github.com/user-attachments/assets/2a20f8be-6da8-4434-acf5-3792b2c8a425)
![chrome_FdCpzk92ar](https://github.com/user-attachments/assets/88006b32-32e5-456e-ba4a-827a194c1c67)

**Comment by daniluk4000** [comment]
Does this look valid?

![image](https://github.com/user-attachments/assets/c5247e33-4af4-4794-a7ec-9219aaaffe71)

![image](https://github.com/user-attachments/assets/5253db6a-dca8-40b2-9dda-112f29a882ca)

**Comment by zladatm** [comment]
> Does this look valid?
> 
> ![image](https://private-user-images.githubusercontent.com/10450717/354918613-c5247e33-4af4-4794-a7ec-9219aaaffe71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTM0NTQsIm5iZiI6MTcyMjc5MzE1NCwicGF0aCI6Ii8xMDQ1MDcxNy8zNTQ5MTg2MTMtYzUyNDdlMzMtNGFmNC00Nzk0LWE3ZWMtOTIxOWFhYWZmZTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE3MzkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkN2Q2ZDc5MGQyMDc5MThmYjA5YjE1MThmNDNjZjI0M2NlN2NmYjUyZDM1ZTBjMGJiYzE2MDRhMmVjM2E3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hEtgslZn99sE-ASAtoielg1Ob5DYydsq-wZ6aouxldc)
> 
> ![image](https://private-user-images.githubusercontent.com/10450717/354918623-5253db6a-dca8-40b2-9dda-112f29a882ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTM0NTQsIm5iZiI6MTcyMjc5MzE1NCwicGF0aCI6Ii8xMDQ1MDcxNy8zNTQ5MTg2MjMtNTI1M2RiNmEtZGNhOC00MGIyLTlkZGEtMTEyZjI5YTg4MmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE3MzkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NmIwZjAyYWVjYWYyYjBjMDUwMjViYmQwOTg3NTFjNzgxNGFkN2JjNGE2NGZkNjU1ZTAyZGQwNWRiMTg5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zgRPz2g1UP3dhBDUZ4-9woWepxvy0f_U-b45b2d-1Ww)

Yes that looks accurate. There is no such position as SCT_DEP only LAX_DEP but I suppose if we ever made one, that’s what it would cover.

**Comment by daniluk4000** [comment]
Nice, thanks! Fix will be available in 0.4.4.

**Comment by zladatm** [comment]
I see that #289 caused an issue, but any update here would be appreciated. Many pilots who have become reliant on VATSIM-Radar are not contacting the right controllers.

**Comment by daniluk4000** [comment]
> I see that #289 caused an issue, but any update here would be appreciated. Many pilots who have become reliant on VATSIM-Radar are not contacting the right controllers.

0.4.4 will be out in coming days.

**Comment by nickchristopher** [comment]
@daniluk4000 This bug has reappeared with 0.5.0.

Note: prior to this release, SCT_APP did work correctly. However, we noticed a bug still. Once SCT_APP logged in, LAX_DEP airspace appeared. After a few moments, it would change to the correct SCT_APP airspace.

![6UzCWcs](https://github.com/user-attachments/assets/183d1fbb-d862-47a4-967c-e8834d04e538)
