### ISSUE TITLE
CHI_Z_APP (C90 TRACON) shows only as a circle.

### ISSUE THREAD

**Issue by Saluki00** [VATSIM-Radar/vatsim-radar#222]
### Your Vatsim CID

1634151

### Radar version

0.4.3

### Describe your issue

The Chicago TRACON, C90, under the callsign CHI_Z_APP (or any other CHI_X_APP variant) shows only as a circle on the radar map.  I briefly spoke with Danila about this and was told "have seen CHI issues before" and that VATSIM-Radar pulls data from simaware.  I looked at the simaware github and noticed the geojson files are no longer there.  Maybe this is the issue?  Anyway.  I can provide a geojson for the outline of C90 if needed.  Last I saw simaware's data has been a mess for some time and I stopped using the site.  IIRC, they were only showing a circle as well, but could be mistaken.

### Reproduction steps

None

### Platform

Windows 10

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
![image](https://github.com/user-attachments/assets/d9a0886c-faba-4f68-bbeb-90518d5b5f95)

Will be fixed in 0.4.4

**Comment by jivebiscuit** [comment]
Hey Danila, I think we're seeing this at Houston I90 now. The large circle is labeled KIAH when I90_D_APP is online.
![image](https://github.com/user-attachments/assets/e0dded02-162a-4334-938f-a3d12cb7bb88)
