### ISSUE TITLE
Missing Periods and small typo

### ISSUE THREAD

**Issue by Hypekingfish** [VATSIM-Radar/vatsim-radar#233]
### Your Vatsim CID

1630701

### What do you suggest?

![image](https://github.com/user-attachments/assets/17ee79ef-f7cd-4270-b726-8126e4e753be)

There should be a "BE" in between COULD and THE

### Why do you need that?

Just so it's proper

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
![image](https://github.com/user-attachments/assets/dbf0f260-0f9c-4fef-b380-3d1ecc41b9ba)

(don't show this to my English teacher)
