### ISSUE TITLE
Generic Icons

### ISSUE THREAD

**Issue by Dflight94** [VATSIM-Radar/vatsim-radar#235]
### Your Vatsim CID

1157040

### What aircraft icon(s) do you suggest to add

Would there be anyway to insert a generic icon for type of aircraft (single/twin/jet) not necessarily make and model of aircraft? I know model matching for every aircraft would take a while to do but, as a quick thing I think this would be a good thought.

For example: When flying a Baron/C310/Seneca, a generic "twin engine" icon is present vs the generic "commercial jet" icon that is currently present.

![twin](https://github.com/user-attachments/assets/898ced6f-726a-4e94-9cc1-f4f1a9889be8)

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by daniluk4000** [comment]
It is generic, but requires model matching.

Regarding this one, please say what of our existing icons work for it: https://github.com/daniluk4000/vatsim-radar/tree/next/src/assets/icons/aircraft

**Comment by DotWallop** [comment]
So, I have no issue marking these ICAO codes as well, but that ICAO code is invalid. It should be filed as BE58, which is the ICAO code for all Baron B58 types. That's likely why it reverts to that. I will make a B58 Baron now.

**Comment by Dflight94** [comment]
I guess if VATSIM is only recognizing one ICAO code for all the variants then I will be filing under that from now on. I was under the impression that the BE58 was for the non-pressurized version and the B58T was for the pressurized and Turbo versions.  Thanks for the explanation and making one! I appreciate all of your hard work.

**Comment by DotWallop** [comment]
> I guess if VATSIM is only recognizing one ICAO code for all the variants then I will be filing under that from now on. I was under the impression that the BE58 was for the non-pressurized version and the B58T was for the pressurized and Turbo versions. Thanks for the explanation and making one! I appreciate all of your hard work.

Mmm, I am not too sure to be honest. VATSIM accepts "all" codes, so you might very well be correct. I will make it so it'll work both as BE58 and B58T. :)

**Comment by DotWallop** [comment]
> Is it also possible a Type of Icons for V Wing aircraft like the CL60 or GLEX?

Danila have to respond whether or not this can be done for placeholders, but both the CL60 and the GLEX is on the list to be made. :)
