### ISSUE TITLE
Meridian Approach (KNMM/KMEI) border not displaying.

### ISSUE THREAD

**Issue by PulsarPilot** [VATSIM-Radar/vatsim-radar#237]
### Your Vatsim CID

1397568

### What do you suggest?

Add/fix the border for Meridian Approach within ZME.

### Why do you need that?

It helps to encourage traffic at the fields within the tracon.

### Additional info

![nmm missing border](https://github.com/user-attachments/assets/3b87c0ec-803f-4e86-adbb-f38ffe3bf70e)
What currently displays while controlling the tracon here.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by Vainnor** [comment]
To add to this, when zoomed all the way out, it shows up even though there is no one online. 
![Screenshot 2024-08-03 195716](https://github.com/user-attachments/assets/ce83bc39-bc61-407a-ae0c-559561fbdb27)

**Comment by daniluk4000** [comment]
um...

@Vainnor what's the callsign?

**Comment by Vainnor** [comment]
NMM

**Comment by daniluk4000** [comment]
> NMM

NMM_APP?

**Comment by daniluk4000** [comment]
![image](https://github.com/user-attachments/assets/92339444-5724-44b4-83a7-e861f505852c)

Will be available in 0.4.4

**Comment by Vainnor** [comment]
I am not sure. The problem was that they were not online and the rage would only show up when fully zoomed out.

**Comment by daniluk4000** [comment]
I meant that I fixed this :)
