### ISSUE TITLE
Certain new aircraft icons are scaled too big

### ISSUE THREAD

**Issue by DotWallop** [VATSIM-Radar/vatsim-radar#241]
### Your Vatsim CID

1227980

### Radar version

v0.4.4-alpha.2

### Describe your issue

Several aircraft (only found F35 and F16) in the new aircraft icon list are scaled incorrectly, being way too big. This does not apply to all icons. Size table is correct.

![image](https://github.com/user-attachments/assets/69ec197c-882e-46f2-9d93-ff8353cb0c9d)
![image](https://github.com/user-attachments/assets/0c5f786e-2e5d-4c36-8f60-9901612f5394)

### Reproduction steps

Find aircraft, look at aircraft

### Platform

Windows, Edge

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
Seems to be OK since 0.5.0
