### ISSUE TITLE
Cabri G2 helicopter, G2CA, icon (Shows as plane)

### ISSUE THREAD

**Issue by John14146** [VATSIM-Radar/vatsim-radar#249]
### Your Vatsim CID

1698529

### What aircraft icon(s) do you suggest to add

Cabri G2 helicopter 'G2CA'. Use icon ec45.svg

### Improve existing matching

ec45.svg

### Additional info

The Cabri G2 is a default heil with MSFS. The icon ec45 is almost perfect. But that shows a 4 blade, the cabri is 3 blade. Not important, Its better than showing a fix wing, as it currently is. 

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by John14146** [comment]
New line of code proposed

**Comment by DotWallop** [comment]
@John14146 just to confirm, when it displays as a plane - have you filed a flight plan at the time?

**Comment by John14146** [comment]
Yes, with type G2CA

**Comment by Atriusftw** [comment]
It's the same case with EC45 and H160.

**Comment by DotWallop** [comment]
> It's the same case with EC45 and H160.

What is? So, the H160 is already in the main branch, and works. The EC45 is in the next branch and works too.

However, it does require you to file a flight plan, as VATSIM Radar has no way of reading what aircraft code you _log on_ with, only what you file in your flight plan.

**Comment by Atriusftw** [comment]
> > It's the same case with EC45 and H160.
> 
> What is? So, the H160 is already in the main branch, and works. The EC45 is in the next branch and works too.
> 
> However, it does require you to file a flight plan, as VATSIM Radar has no way of reading what aircraft code you _log on_ with, only what you file in your flight plan.
> 
> @daniluk4000 I am guessing there's nothing to do about that atm.

Flew on a flight plan with the EC45 earlier today and it did not load the icon, but if it's in a different branch that explains it (=
