### ISSUE TITLE
UX enhancement - Auto-hide aircraft info on mouse movement

### ISSUE THREAD

**Issue by DotWallop** [VATSIM-Radar/vatsim-radar#251]
### Your Vatsim CID

1227980

### What do you suggest?

A small pet-peeve I frequently encounter is when scrolling through the aircraft info popups, and find myself getting stuck at one of them when I wanted it to disappear. I identified it as happening when I move the mouse over the top bar of the popup. Would it be a possibility of hiding the tag if you hover over here?
![image](https://github.com/user-attachments/assets/04fb4e3f-5560-4fe9-81b4-163428d43cb0)

Of course, not a definitive need - but at least I find myself having to wiggle the mouse several times to get rid of it.

### Why do you need that?

In order to smoothly transition between the different aircraft popups

### Alternatives

Having to move the mouse much farther than I would have needed to.

### Additional info

Alternative would to have a checkbox for "auto-hide aircraft information".

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Wouldn't this be too unintuitive?

Also, how would auto-hide work?

**Comment by DotWallop** [comment]
Should have clarified, should hide when cursor hits the boxed area, as there’s no reason to interact here. Not sure however.

**Comment by DotWallop** [comment]
> Also, how would auto-hide work?

Basically disable the context buttons in the popup panel, so that when the cursor moves away from the aircraft icon, the popup hides even if the cursor is over it. 

.. if that makes sense. Can describe more in detail if needed.
