### ISSUE TITLE
Leaderboard for top 10 most popular airports at the time

### ISSUE THREAD

**Issue by OpenFire78** [VATSIM-Radar/vatsim-radar#255]
### Your Vatsim CID

1612721

### What do you suggest?

Simaware also has this feature where it displays the 10 airport that have the highest amount of arrivals and departures. This leaderboard also displays the arrival and departure number for the airports. For example, at a given moment in time, KORD has the highest number of arrivals and departures compared to all other airports. So KORD is ranked #1. EGLL has the second highest amount of arrivals and departures, so it’s second on the leaderboard, and so on. Additionally, under the airport icon should be the cab positions that are staffed. 

### Why do you need that?

It would be a beneficial addition for people trying to see what the most popular airport is during an event or just on a normal day. 

### Alternatives

Simaware has this implemented 

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Already planned

**Comment by RoboFun01** [comment]
Isnt this completed?

**Comment by daniluk4000** [comment]
Ah yes
