### ISSUE TITLE
Highlight "Map Last Updated" time if out of date

### ISSUE THREAD

**Issue by m-9c** [VATSIM-Radar/vatsim-radar#257]
### Your Vatsim CID

974571

### What do you suggest?

Probably a niche/low priority request :)

When network connectivity is lost, VATSIM Radar obviously won't receive any updates but will still "look" normal.

I suggest introducing logic so that if the data in VATSIM Radar is out of date (eg time since Map Last Updated > 5 minutes, or similar), the lack of currency is highlighted to the user.

Eg,
![image](https://github.com/user-attachments/assets/c4ba750a-63d6-4f1b-be76-2bdc61bc446f)

### Why do you need that?

This will help minimise confusion if a user is using VATSIM Radar on a device that has lost network connection.

Could also help minimise confusion if the connection between the VATSIM API and VATSIM Radar does down

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by Nyan404** [comment]
Seems like good idea @daniluk4000

**Comment by daniluk4000** [comment]
I was thinking of that for past few weeks actually.
