### ISSUE TITLE
PHNL_ATIS and HNL_GND displays two different boxes

### ISSUE THREAD

**Issue by reiji69** [VATSIM-Radar/vatsim-radar#258]
### Your Vatsim CID

1679151

### Radar version

0.4.3/0.4.4-alpha.2

### Describe your issue

PHNL_ATIS and HNL_GND (presumably also HNL_TWR) shows up as two different boxes (PHNL/HNL)
![image](https://github.com/user-attachments/assets/fe575200-9f5f-4687-a989-db87c7a77ee5)

### Reproduction steps

It will be demonstrated on the map when PHNL_ATIS and HNL_GND are both online.

### Platform

Windows Chrome Version 126.0.6478.185

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Fixed in next

![image](https://github.com/user-attachments/assets/35b1444c-1dbe-4a3a-b791-ed6ec8a0376a)
