### ISSUE TITLE
Direct Link to Callsign

### ISSUE THREAD

**Issue by malanquerido** [VATSIM-Radar/vatsim-radar#259]
### Your Vatsim CID

1042467

### What do you suggest?

Right now we have a direct link to the CID via ?pilot=CID parameter. I’d love to also have a link to a callsign via ?callsign=ABC123.

### Why do you need that?

This would be awesome for VAs to link to certain flight, if they are online, without querying the CID from the data feed first.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by DotWallop** [comment]
Yes, this would be hugely beneficial, also to Supervisors. 😄 🔨

**Comment by daniluk4000** [comment]
https://vatsim-radar.com/?pilot=AFL352

**Comment by malanquerido** [comment]
> https://vatsim-radar.com/?pilot=AFL352

Interesting, after opening a new browser session it works like charm. Thx <3
