### ISSUE TITLE
Display Controllers Break Status

### ISSUE THREAD

**Issue by bencodes07** [VATSIM-Radar/vatsim-radar#264]
### Your Vatsim CID

1601613

### What do you suggest?

As a controller you can type .break to make other controllers about to see, that you are closing. I think this would be good for pilots to see.

### Why do you need that?

When pilots want to start a flight they often look at vatsim-radar to see, which controllers are online. If those pilots would know, that a specific controller was about to close, they would not start a flight, where the controller would close any minute.

### Alternatives

I do not think there are any alternatives implemented. A pilot could potentially connect his ATC client as an observer however that is not really a good solution.

### Additional info

Thank you for your amazing work :D

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by DotWallop** [comment]
Is this even exposed? I was under the impression that was purely internal within the ATC client.

**Comment by bencodes07** [comment]
That is very possible. I don't have any information about that unfortunately. It looks like it though

**Comment by daniluk4000** [comment]
Yeah we probably won't know that, but let's add considering for now.

**Comment by daniluk4000** [comment]
Not possible with current data we have
