### ISSUE TITLE
TAF Decoder Times Wrong

### ISSUE THREAD

**Issue by ntilley905** [VATSIM-Radar/vatsim-radar#267]
### Your Vatsim CID

1013419

### Radar version

0.4.3

### Describe your issue

In the TAF decoder, the times seem to duplicate the hour into the minutes. Example provided below. The TAF minutes in the provided example are all zero.
![image](https://github.com/user-attachments/assets/1e186747-1e88-4e1f-8005-6fbdf91329ef)

### Reproduction steps

Select any airport, in airport info tab open the TAF section and observe the times.

### Platform

Debian 39, Firefox 129.0

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Lol
