### ISSUE TITLE
SY-C_GND creates duplicate 'Airport' box, not present in Production

### ISSUE THREAD

**Issue by m-9c** [VATSIM-Radar/vatsim-radar#276]
### Your Vatsim CID

974571

### Radar version

v0.4.4-alpha.2

### Describe your issue

When both SY_GND and SY-C_GND are logged in, two "airport boxes" are visible. One contains the "normal" unit, the other has only SY-C_GND

![image](https://github.com/user-attachments/assets/934a2827-aaf6-47ea-b7f6-22109ae2553b)
![image](https://github.com/user-attachments/assets/8df8ccec-9d0e-4083-8994-da9da7b4f313)

This does not appear in Production. In Production, SY_GND and SY-C_GND appear in the same popup box. 
![image](https://github.com/user-attachments/assets/da152d6d-6633-4da7-8ccb-5847931477b5)

### Reproduction steps

Have both SY_GND and SY-C_GND logged in.

### Platform

Windows, Version 127.0.6533.120 (Official Build) (64-bit)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
Nice, thanks!

**Comment by daniluk4000** [comment]
Fixed in Beta 1

![image](https://github.com/user-attachments/assets/1c03b5dd-507c-4cc6-af5f-0663b4a6f996)
