### ISSUE TITLE
LAX Tower shows as SoCal Combined towers. Other SoCal airports have this same problem

### ISSUE THREAD

**Issue by VeIocityy** [VATSIM-Radar/vatsim-radar#289]
### Your Vatsim CID

1573809

### Radar version

0.4.3

### Describe your issue

The LAX tower cab shows like this.  
![image](https://github.com/user-attachments/assets/05eb9824-4272-4e98-882d-e5ed51704811)
(it also shows SCT as the facility)
SNA and ONT shows their respective SoCal approach **sector**, not the airport
![image](https://github.com/user-attachments/assets/67b3aca4-4686-4f47-9039-74c66e8673f7)
![image](https://github.com/user-attachments/assets/d0cfc340-6e82-4579-a0cd-6de9d4e2e83b)

### Reproduction steps

View any SoCal airport that fall under the list above and observe the names.

### Platform

Windows, 127.0.6533.120 (Official Build) (64-bit) (cohort: Stable) 

### Additional info

Feel free to reach out on Discord `velocity.` if I was unclear

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
My apologies for that

**Comment by VeIocityy** [comment]
![image](https://github.com/user-attachments/assets/1d79f87f-a79b-4cab-81b6-c70eb83bbe80)
https://github.com/VATSIM-Radar/vatsim-radar/issues/216 is back

**Comment by daniluk4000** [comment]
> ![image](https://private-user-images.githubusercontent.com/66051892/360718284-1d79f87f-a79b-4cab-81b6-c70eb83bbe80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTg3MTYsIm5iZiI6MTcyNDM5ODQxNiwicGF0aCI6Ii82NjA1MTg5Mi8zNjA3MTgyODQtMWQ3OWY4N2YtYTc5Yi00Y2FiLTgxYjYtYzcwZWI4M2JiZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3MzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYTBiMjExY2M0OGUzZThjY2JjYmVmOWY2MGI0MDZmYjk4MWM4OTYyNDhkZGNiNzE2M2ZiZjE5OTkyYWJiODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qrhVKMktPmvArhZojIz-gDeNXCXjf6J7ZPbCfcxE-Ic) #216 is back

Fix is still not released for 216 for now
