### ISSUE TITLE
Inbounds and Outbounds

### ISSUE THREAD

**Issue by FlyforLive** [VATSIM-Radar/vatsim-radar#315]
### Your Vatsim CID

1667561

### Radar version

 v0.4.3-1

### Describe your issue

Hello i notised that the In and outbounds are not the Same in the Airport Menu and the Normal Map
<img width="593" alt="Screenshot 2024-08-30 211725" src="https://github.com/user-attachments/assets/a0ba842d-e93f-4d9b-93b2-296bc88e8899">

### Reproduction steps

I dont now that. I am just l my Chrome

### Platform

Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
That is not a bug. You will be able to change that some day
