### ISSUE TITLE
Icons for various GA Aircraft

### ISSUE THREAD

**Issue by LeNinjaHD** [VATSIM-Radar/vatsim-radar#332]
### Your Vatsim CID

1596968

### What aircraft icon(s) do you suggest to add

- Piper PA28 (Has multiple ICAOS, wildcard like P28*)
- Piper PA24 (PA24)
- Beechcraft Duke (BE60 & B60T)
- Dimona (DIMO, is a popular Motorglider)

### Model matching

Dimona icon could be used for all Motorgliders (SF25, G109)

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by daniluk4000** [comment]
PA28/PA24 will be added in 0.5.0

**Comment by Dflight94** [comment]
Requesting the twin Cessna series aircraft as well please. (C310 AND C414) 
![414A-line-art-top-view+copy](https://github.com/user-attachments/assets/3218bf05-89ec-4ecd-a50c-91887098197e)
![T310R-line-art-top-view+copy](https://github.com/user-attachments/assets/fb048785-9bed-4655-be8e-bd7d6310028e)

**Comment by DotWallop** [comment]
Designed!
