### ISSUE TITLE
C700 Correct Icon

### ISSUE THREAD

**Issue by dinellirn** [VATSIM-Radar/vatsim-radar#338]
### Your Vatsim CID

1604647

### What do you suggest?

Hi!
The icon for the Cessna Citation Longitude (C700) could be improved. It currently seems to be the silhouette of a Citation Sovereign (C680) which has quite a different wing profile.

![21151-mid-wm](https://github.com/user-attachments/assets/ce6b636a-d47c-496d-973a-085c626f3db4)
Citation Longitude, note the swept wing profile

![images-112](https://github.com/user-attachments/assets/3a7a8fa0-28f4-4d35-b770-23f38b66d9d1)
Citation Sovereign (current icon)

### Why do you need that?

To reflect correctly the model of the aircraft in relation to the icon. The current icon could then be correctly alocated to the C680

### Alternatives

As a compromise, the current icon for the Citation X (C750) could also be used for the C700, as it is a bit more similar to the Longitude's profile (albeit the Citation X has larger engines and the wings are more swept back).

![c750](https://github.com/user-attachments/assets/dd0e0a55-cbd3-41fa-a3ee-5b43d6ef27ca)
C750's current icon

### Additional info

Thanks for the incredible work on Vatsim Radar!

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Model matching will be added in 0.5.0. This issue will remain open

**Comment by DotWallop** [comment]
Huh, you're right - this was surprisingly hard to find. Added to to-do list.
