### ISSUE TITLE
YMML Approach Hidden behind TWR/GND/ATIS icons

### ISSUE THREAD

**Issue by Synergy73** [VATSIM-Radar/vatsim-radar#340]
### Your Vatsim CID

1814230

### Radar version

v0.4.4

### Describe your issue

YMML Approach icon is hidden behind the TWR/GND/ATIS icons
![image](https://github.com/user-attachments/assets/3ea5e8cc-638a-4aae-8b42-5d3d80a358f3)
![image](https://github.com/user-attachments/assets/d69e4680-0bbf-40a2-b454-6c32c828e8ec)

### Reproduction steps

Look at YMML when approach and (one of:) TWR/GND/ATIS/DEL are online.

### Platform

Windows 10, Chrome Version 128.0.6613.119 (Official Build) (64-bit)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
SimAware TRACON issue. Staff has to edit this in their project
