### ISSUE TITLE
BN-TSN_FSS doesn't display correctly

### ISSUE THREAD

**Issue by joelrichters** [VATSIM-Radar/vatsim-radar#344]
### Your Vatsim CID

891193

### Radar version

0.4.4

### Describe your issue

BN-TSN_FSS covers multiple smaller sectors, however on this map it only shows as the primary sector.

### Reproduction steps

Just log on as BN-TSN_FSS

### Platform

windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Has to be changed in VatSpy by local staff: https://github.com/vatsimnetwork/vatspy-data-project

**Comment by daniluk4000** [comment]
Also, is display same between VATSIM Radar and VatSpy? If yes, I'm right, if not, please send screenshots
