### ISSUE TITLE
Aircraft type and groundspeed not popping up after filing flightplan

### ISSUE THREAD

**Issue by GermainDeDuck** [VATSIM-Radar/vatsim-radar#345]
### Your Vatsim CID

1696195

### Radar version

v0.4.4

### Describe your issue

I was flying, noticed I didnt have a flightplan so I filed one. Looked on the radar and saw the aircraft type and groundspeed dissapeared.

### Reproduction steps

Take off without flightplan, then inflight file one and keep an eye on the aircarft. After re selecting or reloading, its still not appearing

### Platform

Windows - Google Version 126.0.6478.127 (64 bit)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Seems like API bug on 3rd party side. Expect ~30s delay before it appears though. I have flought yesterday and couldn't reproduce it
