### ISSUE TITLE
YMML_APP showing incorrectly

### ISSUE THREAD

**Issue by perryMELENOHRST** [VATSIM-Radar/vatsim-radar#347]
### Your Vatsim CID

1655804

### Radar version

v0.4.4

### Describe your issue

YMML_APP is appearing underneath the TWR/APP/DEL "block", meaning that it becomes near impossible to see detailed based on Approach.

![image](https://github.com/user-attachments/assets/536f3e5f-f596-43d7-924a-e3f0b0359095)

### Reproduction steps

View VATSIM Radar when Tower/when there is atis on the airport. Then, you can see Approach is underneath that tab.

### Platform

Windows, Chrome v128.0.6613.120

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Bug in https://github.com/vatsimnetwork/simaware-tracon-project

Should be fixed by local staff
