### ISSUE TITLE
Traffic or Controllers in Oceania does not display on Vivaldi Brwoser

### ISSUE THREAD

**Issue by ViceSergal** [VATSIM-Radar/vatsim-radar#349]
### Your Vatsim CID

1847847

### Radar version

0.4.4

### Describe your issue

VATSIM-Radar does not show traffic in the oceania area on the Vivaldi browser. On the first time visiting the site, traffic displayed, however traffic disappears on the next visit to the site.
![image](https://github.com/user-attachments/assets/4c639d3e-4a28-4913-be35-0a8352b2c39c)

Traffic in other areas shows as expected.
![image](https://github.com/user-attachments/assets/b7458ed8-bb67-4fd6-846a-7e5b86094343)

### Reproduction steps

Install Vivaldi, visit vatsim-radar once, close vivaldi, open vivaldi, visit vatsim radar.

### Platform

Windows 10, Vivaldi 6.9.3447.41

### Additional info

Clearing cookies, removing browser addons, re-installing vivaldi did not fix this issue for me. Cannot reproduce the same issue on edge or chrome.

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by ViceSergal** [comment]
Additional info, seems as though it's to do with panning the map. Pan far left and no traffic in AU, pan far right and no traffic in the US.
![image](https://github.com/user-attachments/assets/53dfd8fe-d9a7-43d7-875a-cf1e12c36b01)
![image](https://github.com/user-attachments/assets/0d63df28-ae49-47eb-8ec0-92cf7db811ed)

**Comment by daniluk4000** [comment]
For now, this is wontfix

**Comment by daniluk4000** [comment]
We only have single world developed
