### ISSUE TITLE
List not refreshing in controller view

### ISSUE THREAD

**Issue by UDomonkos** [VATSIM-Radar/vatsim-radar#354]
### Your Vatsim CID

1623074

### Radar version

v0.4.4

### Describe your issue

![Image](https://github.com/user-attachments/assets/79562529-8ef0-4047-bcd5-2d4e67746326)
The list does not show departing aircraft (there should be 3 of them)

### Reproduction steps

Just left the controller view open, if I refresh, the list works normally

### Platform

windows 11, latest firefox

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Found root cause after all those months
