### ISSUE TITLE
Map updates are inconsistant and somtimes outdated

### ISSUE THREAD

**Issue by YotamKorah** [VATSIM-Radar/vatsim-radar#360]
### Your Vatsim CID

1720165

### Radar version

0.4.4

### Describe your issue

When i was flying today and tracking myself using vatsim-radar I've noticed many times where the "Map last updated" timestamp kept changing inconsistently. For about an hour i noticed that sometimes the time moved back, every now and then it even showed in orange as it was over a minute out of date.

 ![image](https://github.com/user-attachments/assets/904c1eab-ce43-4f56-9f6b-7378b5b6a3c7)

### Reproduction steps

watch it during peak traffic I guess.

### Platform

Windows, Firefox 130

### Additional info

From my (probably limited) understanding of the application there is a worker container that fetches the information for the application and it is saved locally on the container host. assuming there are multiple hosts this issue may be solved either by saving the info to a database or cache (redis probably) or creating a shared volume for the files so that all application pods will have the most up to date info.

P.S. I did not find any contributing guidelines so I would like to note that I am happy to help with any containers/deployment issues if there is the need.

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
That probably depends on your clock sync. That's an issue I inproduced in 0.4.3

**Comment by YotamKorah** [comment]
> That probably depends on your clock sync. That's an issue I inproduced in 0.4.3

I don't believe the issue is client side as the timestamps I saw jumped forward and backward inconsistently.

Also, if this is a known issue added in 0.4.3 than out of curiosity what is the change that caused it?

**Comment by daniluk4000** [comment]
> > That probably depends on your clock sync. That's an issue I inproduced in 0.4.3
> 
> I don't believe the issue is client side as the timestamps I saw jumped forward and backward inconsistently.
> 
> Also, if this is a known issue added in 0.4.3 than out of curiosity what is the change that caused it?

It should not go backwards... I'll take a look, probably caused by mismatch between two update types.

Change was that we now send real update date from our backend rather then just setting current date on frontend.

If your clock is de-synchronized, that can cause updates to look like very delayed or be in "future".

**Comment by daniluk4000** [comment]
Also, if you saw this last saturday when we had overload, it could really be delayed due to high load. If you see this all the time, that's definetly it.

**Comment by YotamKorah** [comment]
> It should not go backwards... I'll take a look, probably caused by mismatch between two update types.

This makes more sense to me. My clock was fine but the updates to the time displayed seemed to be almost random.


> Also, if you saw this last saturday when we had overload, it could really be delayed due to high load. If you see this all the time, that's definetly it.

And yes the issue mostly disappeared by the time I finished my flight and there were about half as much traffic on VATSIM as when I noticed the issue. As I wrote in the start I believe this to be a scaling issue and not necessarily a coding issue. Or maybe I just think that because I do DevOps lol

Anyway I'd like to extend my offer to help with the deployment and architecture of the app if there's ever a need.

**Comment by daniluk4000** [comment]
> Anyway I'd like to extend my offer to help with the deployment and architecture of the app if there's ever a need.

I'll keep that in mind, hopefully will do on our own. Migrating to kubernetes with auto-scale next week.

If you noticed it on this event with 2100 traffic in VATSIM Radar, it could be scaling issue yeah. Seems like tracks traffic eat too much.

Btw, we have nginx config here, that includes our current temporal load balancer: https://github.com/VATSIM-Radar/vatsim-radar/tree/next/.config/nginx

If you notice anything to improve, feel free to open PR with optimization changes.

**Comment by YotamKorah** [comment]
Migrating to k8s would likely solve this issue but may cause others. I looked over the ngnix config and found no clear issues.
I believe we can close this issue untill after the migration and if it persists we can reopen and see what can be done.
good luck with the migration!

**Comment by daniluk4000** [comment]
> Migrating to k8s would likely solve this issue but may cause others. I looked over the ngnix config and found no clear issues. I believe we can close this issue untill after the migration and if it persists we can reopen and see what can be done. good luck with the migration!

Thanks!

And I'll keep this open, since timer should only update on single type of updates, and respect clock desync
