### ISSUE TITLE
Request: Correct Assignment of Ukrainian Airports to VatEUD Division

### ISSUE THREAD

**Issue by rostykk** [VATSIM-Radar/vatsim-radar#361]
### Your Vatsim CID

1524572

### Radar version

Latest

### Describe your issue

Hey Danila,
Just wanted to point out that the Ukrainian airports and division have been part of VatEUD for a while now.  Seems like you're living in a dream world thinking they're still under the RUS division.  Maybe it's time to wake up and update your information? 

### Reproduction steps

Search for any UKxx airport, look at details page, location
![Screenshot_20240915-102344_Chrome](https://github.com/user-attachments/assets/3dda60ba-ddaf-45ad-8010-0780a5367f13)

### Platform

All

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Hey! It's not me living here.

![image](https://github.com/user-attachments/assets/5953d243-d92f-45e0-aa38-153f18d5cd69)

https://my.vatsim.net/api/v2/aip/airports/UKBB

Please contact your staff in order for them to correct division for their airports.

**Comment by rostykk** [comment]
thanks! will coordinate with stuff
