### ISSUE TITLE
Luxembourg labeled as part of Belgium

### ISSUE THREAD

**Issue by Temptica** [VATSIM-Radar/vatsim-radar#362]
### Your Vatsim CID

1366436

### Radar version

 0.4.4

### Describe your issue

When clicking on Luxembourg airport, it says it's part of Belgium. Though, Luxembourg airport is actually part of the country of Luxembourg.
![image](https://github.com/user-attachments/assets/2586a525-db6e-4a31-8877-0b345195f084)

### Reproduction steps

Click on ELLX on the map, then go to Info & weather.

### Platform

windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Okay, sorry. This is returned by VATSIM AIP. 

Local staff should be able to fix this.

https://my.vatsim.net/api/v2/aip/airports/ELLX

**Comment by Temptica** [comment]
Hi thereHa. Intresting one. I’m actually local staff there, I’ll get this sorted then! Would you like me to update you when it is fixed or will it get changed automatically? Best RegagdsNicolasOp 19 sep 2024 om 20:03 heeft Danila Rodichkin ***@***.***> het volgende geschreven:﻿
Okay, sorry. This is returned by VATSIM AIP.
Local staff should be able to fix this.
https://my.vatsim.net/api/v2/aip/airports/ELLX

**Comment by daniluk4000** [comment]
Lol! 

It will be automatically updated within 30 minutes since your change.

**Comment by Temptica** [comment]
Alright. It’s already updated in the api. Have a good night!Op 19 sep 2024 om 23:23 heeft Danila Rodichkin ***@***.***> het volgende geschreven:﻿
Lol!
It will be automatically updated within 30 minutes since your change.
