### ISSUE TITLE
BIRD_S1_CTR boundaries are incorrect on vatsim-radar

### ISSUE THREAD

**Issue by romtam** [VATSIM-Radar/vatsim-radar#366]
### Your Vatsim CID

1338465

### Radar version

0.4.4

### Describe your issue

BIRD_S1_CTR is the bandbox sector for Reykjavik Control, however on vatsim-radar the depicted area is only its individual part. It is correct on VAT-Spy, VatScope, etc.

VAT-Spy:
![image](https://github.com/user-attachments/assets/33dc2ace-0b3f-40b8-8150-993d88422505)

vatsim-radar:
![image](https://github.com/user-attachments/assets/59e074cb-67b8-4ca2-90c8-5a122fd27b59)

### Reproduction steps

BIRD_S1_CTR online then check vatsim-radar

### Platform

Windows 11 / Firefox 130

### Additional info

Refer below, the intended coverage area is the west, south, and east sectors (**not** north).

On vatsim-radar only south sector is displayed

![](https://wiki.vatsim-scandinavia.org/uploads/images/gallery/2023-09/sector-diagram-clean.png)
_Source: VATSIM Scandinavia Wiki_

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
> In Iceland the BIRD_S1_CTR (and BIRD_S2_CTR, BIRD_S3_CTR) are bandbox sectors, covering west and east respectively if those sectors are not separately manned.

So this IS a bug on VATSIM Radar side, right?

**Comment by romtam** [comment]
It appears to be that way.

Refer to the screenshots in my original message, the correct coverage is
what is shown on VAT-Spy (bandboxing west, south, and east, which is what
Adrian said), while on VATSIM Radar it shows south only.

**Comment by daniluk4000** [comment]
Raised this issue in Scandinavia Discord, and also included "fix" (not really a fix) to 0.4.5
