### ISSUE TITLE
Airport centered on text, not dot

### ISSUE THREAD

**Issue by fdrake97** [VATSIM-Radar/vatsim-radar#367]
### Your Vatsim CID

1664386

### Radar version

0.4.4

### Describe your issue

small bug but the airport are currently centered on the text, not the dot. 
![image](https://github.com/user-attachments/assets/33c6394c-bfc8-4681-836c-5d4244bbb2ff)
![image](https://github.com/user-attachments/assets/1e1d2d7d-96de-4b38-b016-a358684287f1)

### Reproduction steps

see any unstaffed airport

### Platform

windows 11 chrome

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
That's a feature, since dot only appears when you zoom, otherwise text would not match airport center

Dot only helps to identify airport in contrast with map labels nearby

**Comment by fdrake97** [comment]
I don't see what the point of the dot is then; it seems weird to not have it on the airport, but ok

**Comment by daniluk4000** [comment]
That would make sense if we would show this dot all the time, but we don't do that due to performance reasons, so sorry

**Comment by fdrake97** [comment]
why not remove the dot altogether then? If it's not centered on the airport, it doesn't seem necessary. I feel like on maps in general, a dot on a map is showing you exactly where something is located, and the label is off-center

**Comment by daniluk4000** [comment]
> why not remove the dot altogether then? If it's not centered on the airport, it doesn't seem necessary. I feel like on maps in general, a dot on a map is showing you exactly where something is located, and the label is off-center

People asked for it to better understand that this is airport, and to know which label belong to which location

Actually, I taked another look on your screenshot and I think that dot being centered would be better in order for airport name to not overlap aircraft on ground

So, let's move this back on track :D
