### ISSUE TITLE
Aircraft icons and callsigns cover the airport and online controller labels

### ISSUE THREAD

**Issue by ApocalypsePlease0** [VATSIM-Radar/vatsim-radar#376]
### Your Vatsim CID

1535534

### Radar version

0.4.5

### Describe your issue

Aircraft icons and callsigns are drawn over the airport label when zoomed out.
![Screenshot 2024-09-21 231119](https://github.com/user-attachments/assets/c144a294-29d7-49af-a780-e2d77c9c42b4)
They don't even appear when hovering over it, obstructing any info from being shown.

### Reproduction steps

Find an airport with a lot of ground traffic and try to look at the airport info and/or online controllers.

### Platform

Windows, Firefox 130.0.1

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Indeed reproducable, firefox only... lol

**Comment by daniluk4000** [comment]
Not firefox only, but unauthorized only. Fixed
