### ISSUE TITLE
Add different track viewing settings

### ISSUE THREAD

**Issue by glott** [VATSIM-Radar/vatsim-radar#382]
### Your Vatsim CID

redacted

### What do you suggest?

Add the option to select one of the following options to display tracks for
- Arrivals only (current)
- Departures only
- All airborne traffic
- All traffic

Ideally, if there could be some slight color difference between arrival and departure tracks, that would be great. I think you should also add a toggle to show only visible or show all (separate of choosing which tracks to display).

### Why do you need that?

Better idea about how the traffic situation looks at an airport. 

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by neilenns** [comment]
"Arrivals only" currently includes planes that have already landed and are parked at the gate. Perhaps it can be updated to exclude parked planes, and a new option added like "Arrivals and landed" to cover both states.
