### ISSUE TITLE
Incorrect position of LFLG airport 

### ISSUE THREAD

**Issue by Fowl38** [VATSIM-Radar/vatsim-radar#384]
### Your Vatsim CID

1809758

### Radar version

0.4.5

### Describe your issue

The LFLG airport position is not correct on the map.
The longitude is not correct (latitude seems to be OK).
The position shall be : 45°13'05"N 005°50'55"E
<img width="829" alt="LFLG_airport" src="https://github.com/user-attachments/assets/d3be44ad-ec36-47d2-bf06-bdf5b8e7d61a">
<img width="526" alt="LFLG_chart" src="https://github.com/user-attachments/assets/753cd9be-d448-413b-a409-cea70c0ab718">

### Reproduction steps

Open Vatsim radar and check the position of LFLG

### Platform

Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
This has to be corrected in https://github.com/vatsimnetwork/vatspy-data-project by local staff
