### ISSUE TITLE
ATR 42, ATR 72 (all variations)

### ISSUE THREAD

**Issue by j14a** [VATSIM-Radar/vatsim-radar#395]
### Your Vatsim CID

1682195

### What aircraft icon(s) do you suggest to add

AT46
AT76
![atr-above](https://github.com/user-attachments/assets/68d58bde-46f7-4293-8362-1bd97e3b6dda)

### Model matching

AT46 --> AT43, AT45
AT76 --> AT72, AT73, AT75

### Improve existing matching

No icons currently exist for any variations of these types.

### Additional info

Icons needed for ATR 72 and its shorter version ATR 42. I checked existing icons, there seems to be none for these types. The valid ICAO codes are AT43, AT45, AT46 (can also include AT42 just in case, though it's not a valid code). For ATR 72, codes are AT72, AT73, AT75, AT76.

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by j14a** [comment]
Views from above
![Uploading atr-above.jpg…]()

**Comment by Ramunka** [comment]
i think the currently used icon for de havilland can be used as universal for turboprops of their size

**Comment by feitidede** [comment]
is this still being worked on? I think the AT76 and 46 could use their own icon

**Comment by Ramunka** [comment]
I have no idea if there was any progress. Thought that might be a simplification like the FR24 turboprop icon

**Comment by DotWallop** [comment]
> is this still being worked on? I think the AT76 and 46 could use their own icon

Absolutely, just moving nowadays, but it's high up on my list. 😃
