### ISSUE TITLE
Draw Approach over aircraft

### ISSUE THREAD

**Issue by fdrake97** [VATSIM-Radar/vatsim-radar#405]
### Your Vatsim CID

1664386

### What do you suggest?

All other ATC is drawn above aircraft currently, except Approach/TRACON

### Why do you need that?

It often makes it a little harder to see, hover, click on, etc when there are many aircraft in that area.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
It would be super hard to render text and only text above aircraft, so now whole tracon is drawn above aircraft
