### ISSUE TITLE
Map Text Position Change

### ISSUE THREAD

**Issue by sammckenzie236** [VATSIM-Radar/vatsim-radar#414]
### Your Vatsim CID

N/A - Not a controller

### What do you suggest?

Hi,

I just wanted to submit a request to see if you'd be able to change something to do with how text for ATC control centres is displayed at Melbourne International (YMML). Being my home airport, I find that sometimes if any controllers are on Melbourne ATIS/Delivery/Ground/Tower, then it becomes almost impossible to click on the text box that is for Melbourne Approach/Departures (orange in my screenshots).

If this change is to be implemented, I would suggest that the text box be moved only slightly north or south of the current text box (that displays "YMML" and then the symbols for controllers)

Attachments:
![image](https://github.com/user-attachments/assets/35bb7d9f-0208-496c-94e4-d646c438fcf1)

### Why do you need that?

I would like for this to be added so it is easier to pull up controller details for ML_APP, this would benefit pilots flying out of/into Melbourne as they can find the controller's frequency prior to being handed off to the controller from centre.

### Alternatives

The current alternatives are as follows:
 - Try very hard to click just to the side of the airport text box in an attempt to click the orange box below. It is possible but not practical for pilots already juggling flying their aircraft and talking to ATC.
 - Select another aircraft within Melbourne Departures/Approach's airspace, click the "ATC" tab, click the "Approach/Departure" tab. This works fine now but as I stated before it would be nice if it didn't have to be buried in the details of someone else's flight. This also isn't possible when there aren't any aircraft in the airspace.

### Additional info

Nothing additional to add, I'd be happy to respond to any other questions regarding how the issue should be solved. Also, besides this minor issue, I love this website and use it solely as my Vatsim map when flying, good job everyone who helped make it!

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
https://github.com/vatsimnetwork/simaware-tracon-project

Local staff has to fix this here
