### ISSUE TITLE
Sydney Airport Typo

### ISSUE THREAD

**Issue by Hedgehog-Aviation** [VATSIM-Radar/vatsim-radar#429]
### Your Vatsim CID

1804435

### Radar version

v0.4.5-1

### Describe your issue

YSSY airport, Sydney, when hovered over it shows "Sydney Kingsform-Smith" instead of "Sydney Kingsford-Smith"
This is a simple typo.

### Reproduction steps

Go to Vatsim radar
Find Sydney airport and hover mouse over
Notice incorrect spelling

### Platform

Windows, Opera GX 113.0.5230.135

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Hey! Please contact your staff to correct this in https://github.com/vatsimnetwork/vatspy-data-project
