### ISSUE TITLE
Changing "FIR" to "FIR/ARTCC" in Theme Colors Options

### ISSUE THREAD

**Issue by Daniel-Faria-Filho** [VATSIM-Radar/vatsim-radar#431]
### Your Vatsim CID

1616573

### Radar version

0.5.0-alpha.2

### Describe your issue

In the "Colors" settings in the "Map Settings" option, you can customize the color for the "FIR." I recommend changing this from "FIR" to "FIR/ARTCC" or something similar as all Control Centers in the U.S./VATUSA are considered ARTCCs and not FIRs. 

FIRs are not a thing anywhere in the U.S.

This should be a simple and easy fix. Just a frontend text change so it's more natural to members used to flying in the U.S.
![Screenshot 2024-10-19 091847](https://github.com/user-attachments/assets/57a86ecf-1564-4752-9252-c10547a39a33)

### Reproduction steps

Go to the "Map Settings" tab on the left then click "Colors" on the top. There is an option to change colors for "FIR".

### Platform

Windows 11 / Chrome Latest Version

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by DotWallop** [comment]
Might be pedantic, but aren't they technically still FIR's? The ARTCC is the facility, i.e. the provider, but the FIR is the airspace itself, which would be more appropriate in this context.
E.g.:
**ARTCC** = ZTL
**FIR** = KZTL

This refers to the airspace, not the ATS provider
