### ISSUE TITLE
Explanation Airports Counters

### ISSUE THREAD

**Issue by FlyforLive** [VATSIM-Radar/vatsim-radar#438]
### Your Vatsim CID

1667561

### What do you suggest?

At the moment I still find the airport counters very confusing. If you play around with the mode you can see how it changes. However, the naming of the modes is still a bit strange/hard to understand. Even if Total Depatures is very clear, it is a bit more difficult to understand this function/difference directly with Departing/with GS>0. When does a depature count as an Enroute or Climb? Does Taxi still count as Departing? Al such questions, I still find unanswered, even if these important factors can significantly influence the decision of the settings. The term Horizontal in the prefiles also does not directly describe what is meant by this. Perhaps the wording here could be changed again to make these settings easier for users to understand.

### Why do you need that?

This clarification of the function contributes massively to the understanding of the Airports Counters. For controllers in particular, it can be very helpful to see at a glance how many departures are on the ground or, for example, approximately how many aircraft are arriving. Based on this information, we usually decide whether we open a station or not. If this explanation or reformulation takes place, it helps immensely to find the right setting for oneself and thus the view and the satisfaction by a lot.

### Additional info

At the moment, I have not noticed any bugs in the daily use of Vatsim Radar/they have already been reported

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
I've renamed GS > 0 to "moving only"

**Comment by FlyforLive** [comment]
That looks much better. With the help of the renaming, it is now also easier to understand how the airport counters work. Thanks
