### ISSUE TITLE
Icons for Cirrus Aircraft

### ISSUE THREAD

**Issue by LeNinjaHD** [VATSIM-Radar/vatsim-radar#443]
### Your Vatsim CID

1596968

### What aircraft icon(s) do you suggest to add

SR22 - Cirrus SR22
S22T - Cirrus SR22T
SR20 - Cirrus SR20

Same icon for al of them

### Validation

- [X] I have searched for other requests and didn't found any alike

**Comment by DotWallop** [comment]
Will make SR22. :)

**Comment by LeNinjaHD** [comment]
> Will make SR22. :)

Thanks! Will it be model matched to all the other SR Typecodes?
