### ISSUE TITLE
KFSM not on map

### ISSUE THREAD

**Issue by noah-cpi** [VATSIM-Radar/vatsim-radar#454]
### Your Vatsim CID

1632295

### Radar version

v0.4.5-1

### Describe your issue

The KFSM airport is not popping up on the map

### Reproduction steps

add FSM_TWR, FSM_GND, FSM_DEL

### Platform

windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
That was a VERY rare case
