### ISSUE TITLE
Some aircraft flying missing on vatsim radar. 

### ISSUE THREAD

**Issue by Alexos77** [VATSIM-Radar/vatsim-radar#462]
### Your Vatsim CID

1759504

### Radar version

v0.4.5-1

### Describe your issue

at 11:20 pm 11/2/2024 5 aircraft that were on the network was missing on the radar. I could only see it on volanta or tcas of the plane. This issues occured on KSFO it was uncontrolled so i was using vatsim radar as an awareness.

### Reproduction steps

.

### Platform

Windows, chrome.

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by PantsSlayer9000** [comment]
Still the same issue @ 05:48 UTC

**Comment by daniluk4000** [comment]
Seems like a temporal problem we had. Fixed now. Sorry about that
