### ISSUE TITLE
OMDB Approach not shown

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-Radar/vatsim-radar#464]
### Your Vatsim CID

1116943

### Radar version

Current

### Describe your issue

Since latest simaware TRACON project update, no OMDB approach airspace shown. Shown correctly on VATSpy.

Unable to see any issue with polygon definition at https://github.com/vatsimnetwork/simaware-tracon-project/pull/393

### Reproduction steps

OMDB_APP online

### Platform

Any

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by luke11brown** [comment]
Also no departures on the airfield shown

**Comment by daniluk4000** [comment]
Seems like a temporal problem we had. Fixed now
