### ISSUE TITLE
Adding Aircraft type to Search Bar

### ISSUE THREAD

**Issue by FlyforLive** [VATSIM-Radar/vatsim-radar#465]
### Your Vatsim CID

1667561

### What do you suggest?

I think it would be great if we put the Aircraft type right next to the Callsing. 
![image](https://github.com/user-attachments/assets/38472ecf-e5e5-47c7-aff5-ac0fe2b89702)

### Why do you need that?

It's not really necessary, but It makes the space to the right of the calling not so empty

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by FlyforLive** [comment]
And if you click on an aeroplane or Airport, it would be great if the search menu closes

**Comment by FlyforLive** [comment]
Another point would be to search for names and IDs

**Comment by daniluk4000** [comment]
> Another point would be to search for names and IDs

It's already in it
