### ISSUE TITLE
ENOB_CTR Callsign Wrong

### ISSUE THREAD

**Issue by Azchk** [VATSIM-Radar/vatsim-radar#472]
### Your Vatsim CID

1462126

### Radar version

0.4.5-1

### Describe your issue

Callsign for ENOB_CTR is incorrect. 
![image](https://github.com/user-attachments/assets/8a1a3aa5-b5f7-442b-96af-846374de3a4b)

Should be Bodø Oceanic Control as written in the ATIS, not Bodø Oceanic Radio

### Reproduction steps

ENOB_CTR online

### Platform

Windows 11, Chrome Version 130.0.6723.92 (Official Build) (64-bit)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by Adrian2k** [comment]
Dupelicate of #461
