### ISSUE TITLE
[Display Bug] Cherat Approach (CHR_APP) in Pakistan is showing in France as Chateauroux Approach

### ISSUE THREAD

**Issue by ClipperWings** [VATSIM-Radar/vatsim-radar#474]
### Your Vatsim CID

1161277

### Radar version

0.4.5-1

### Describe your issue

CHR_APP in Pakistan is showing in France as Chateauroux Approach 
![image](https://github.com/user-attachments/assets/fe8e8ae9-fb17-4008-95f1-eac5857c5be4)

### Reproduction steps

Not sure how you can reproduce it unless you get CHR_APP to connect. The photo was attached further up.

### Platform

Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by Adrian2k** [comment]
As I commented on discord - this is Pakustan vACC's fault.
They have started using a logon without even bothering adding it to the vatspy dataset which the majority of VATSIM uses.

The only airport with CHR defined is LFEJ
![image](https://github.com/user-attachments/assets/e11e2b38-8f03-4bc2-8eda-a2e7d99455b9)

**Comment by Adrian2k** [comment]
Well this is the sector, covering OPPS, OPSS, OPBN
![image](https://github.com/user-attachments/assets/1e4b843a-416a-4d68-8e55-bc1ac4033d6f)

None of them has any aliases defined.
```
OPSS|Saidu Sharif|34.8133333|72.3521667||OPLR|0
OPPS|Peshawar Bacha Khan Intl|33.991667|71.516667||OPLR|0
OPBN|Bannu|32.9721667|70.525||OPLR|0
```

**Comment by daniluk4000** [comment]
@Adrian2k is right here. Local staff should fix that in VatSpy datafiles. Closing this as wontfix

**Comment by Iwhite67** [comment]
Hello, UP because is again the case

**Comment by daniluk4000** [comment]
> Hello, UP because is again the case

Okay? This still needs to be fixed by local staff

**Comment by ClipperWings** [comment]
Yes, it's back

**Comment by ClipperWings** [comment]
![Image](https://github.com/user-attachments/assets/79584ba7-13e6-44a6-8728-bdd4cd05efdb)
