### ISSUE TITLE
Click/Hover Area of TRACON ID

### ISSUE THREAD

**Issue by BeaconSlash** [VATSIM-Radar/vatsim-radar#477]
### Your Vatsim CID

813174

### What do you suggest?

Hello,

It is easy tap/click on an ARTCC ID on the live map to see who is controlling that level. It is nearly impossible, however, to tap on a TRACON ID for the same purpose. This is more a problem on a phone, but the difficulty is there on PC as well. 

Please consider increasing the click area size/layer of TRACON IDs.

### Why do you need that?

Would make it possible to see who's working approach control positions more easily.

### Additional info

On a Pixel 8 Pro for mobile.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Will work better in 0.5.0
