### ISSUE TITLE
LFSL incorrectly reported as Toul Rosières iso. Brive-Souillac

### ISSUE THREAD

**Issue by LeCoyote** [VATSIM-Radar/vatsim-radar#478]
### Your Vatsim CID

812070

### Radar version

0.4.5-1

### Describe your issue

![image](https://github.com/user-attachments/assets/42a144e1-8ae9-4cb1-a6ae-4fb80fe79132)
The aircraft in the picture is at Brive-Souillac. The code LFSL was used for Toul-Rosières AB until 2004, but it now designates Brive. Vatsim-Radar seems unaware of this fact.

### Reproduction steps

File a flight from LFSL Brive-Souillac, or check out an existing one.
See VATSIM Radar show it as departing from Toul-Rosières

### Platform

Windows 10, FF 132.0.1

### Validation

- [x] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
That's an issue for local staff and VatSpy database

LFSL|Toul-Rosieres|48.78306|5.48306||LFEE|0

https://github.com/vatsimnetwork/vatspy-data-project
