### ISSUE TITLE
CSB2 aerodrome marked as CYSA

### ISSUE THREAD

**Issue by reiji69** [VATSIM-Radar/vatsim-radar#479]
### Your Vatsim CID

1679151

### Radar version

v0.4.5-1/v0.5.0-alpha.9

### Describe your issue

![image](https://github.com/user-attachments/assets/909221cd-4b5d-4152-ac47-b1b2cfb5b22e)
![image](https://github.com/user-attachments/assets/307b8ec7-42fe-420f-8d15-1e9692104b4d)
![image](https://github.com/user-attachments/assets/2d85a571-a60c-4e54-869d-221f7d99b122)

### Reproduction steps

N/A

### Platform

Chrome Version 130.0.6723.117

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
An issue for VatSpy database and also local staff to make changes

https://github.com/vatsimnetwork/vatspy-data-project
