### ISSUE TITLE
Australian Approach positions are not being included in the Featured Airports Tab

### ISSUE THREAD

**Issue by m-9c** [VATSIM-Radar/vatsim-radar#484]
### Your Vatsim CID

974571

### Radar version

v0.4.5-1

### Describe your issue

Australian Approach positions are not being included in the Featured Airports Tab

![image](https://github.com/user-attachments/assets/cfb1ab16-5886-4b62-9c7c-91d04ef1b1d0)

### Reproduction steps

- Have an Australian approach position online.
- Observe that the Position is not appearing in the Popular Airports, or causing the airport to appear in the quiet airport list as "staffed"

### Platform

Chrome, Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Not this again
