### ISSUE TITLE
LTFJ RWY06R/24L missing

### ISSUE THREAD

**Issue by obvalex18** [VATSIM-Radar/vatsim-radar#494]
### Your Vatsim CID

1715580

### Radar version

v0.4.5-1

### Describe your issue

The 2nd runway in LTFJ, 06R/24L is missing. there is only a runway 06L

### Reproduction steps

Just add RWY06R/24L to the description. 
![image](https://github.com/user-attachments/assets/97e77d78-c38d-4254-a16d-0d87b9fc32c5)

### Platform

windows google chrome. 131.0.6778.70 

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Visible with newest AIRAC (Navigraph subscription)

![image](https://github.com/user-attachments/assets/e8ffaa8b-0ef5-4938-9eb5-8f1567238c36)
