### ISSUE TITLE
EDUU_FUL sector not showing

### ISSUE THREAD

**Issue by nathanwesthead** [VATSIM-Radar/vatsim-radar#496]
### Your Vatsim CID

1465909

### Radar version

v0.4.5-1

### Describe your issue

The ATC sector of EDUU_FUL_CTR does not show on the map. 

![image](https://github.com/user-attachments/assets/fc3706f9-a92a-4edd-868d-82d170dbedb8)
![image](https://github.com/user-attachments/assets/15c2d429-980c-4229-a4ea-aae7bddca5fc)

### Reproduction steps

Routing INBED - BOMBI - DENUT takes through EDUU airspace. Received a contact me from controller prior to BOMBI despite no ATC sector being shown on the map.

### Platform

Windows, Google Chrome

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
This sector is not in VatSpy database
