### ISSUE TITLE
efin sectors

### ISSUE THREAD

**Issue by treeckohelsinki** [VATSIM-Radar/vatsim-radar#501]
### Your Vatsim CID

na

### What do you suggest?

efin sectors for vatsim radar 

### Why do you need that?

efin_j would only show chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.ais.fi/eaip/001-2023_2023_01_26/documents/Root_WePub/ANSFI/Charts/ENR/EF_ENR_6_ACC.pdf h and j and so on

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by Adrian2k** [comment]
The sectors must be submitted by VACC staff here https://github.com/vatsimnetwork/vatspy-data-project
