### ISSUE TITLE
Possibility to set different colors for aircraft on ground and aircraft flying

### ISSUE THREAD

**Issue by Stefano98** [VATSIM-Radar/vatsim-radar#504]
### Your Vatsim CID

1307143

### What do you suggest?

Possibility to set different colors for aircraft on ground and aircraft flying

### Why do you need that?

Would be a nice cool visual feature

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Nice idea
