### ISSUE TITLE
APP color in airport list should match color selected in settings

### ISSUE THREAD

**Issue by fdrake97** [VATSIM-Radar/vatsim-radar#506]
### Your Vatsim CID

664386

### What do you suggest?

Use the color chosen for approach in the popular airports tab 
![image](https://github.com/user-attachments/assets/89b21015-ff18-46f1-8c2d-1d67af4af732)

### Why do you need that?

Would look more consistent.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Text color may become weird after that, so I don't think that's a good addition
