### ISSUE TITLE
Potomac Approach incorrect airspace interpterion 

### ISSUE THREAD

**Issue by macnjlm41** [VATSIM-Radar/vatsim-radar#507]
### Your Vatsim CID

1566297

### Radar version

0.5.0

### Describe your issue

Potomac Approach airspace is incorrect, dont know if this is incorrect data from VATSPY data project or something but its wrong

### Reproduction steps

Look at PCT_APP COMBINED (not just DCA or IAD APP)

### Platform

All

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by Adrian2k** [comment]
Sound like an dataset issue for https://github.com/vatsimnetwork/simaware-tracon-project

**Comment by macnjlm41** [comment]
> Sound like an dataset issue for https://github.com/vatsimnetwork/simaware-tracon-project

It does, however the dataset has not been touched in 2 years.

**Comment by macnjlm41** [comment]
github sucks and I keep closing EVERYTHING

**Comment by Adrian2k** [comment]
> > Sound like an dataset issue for https://github.com/vatsimnetwork/simaware-tracon-project
> 
> It does, however the dataset has not been touched in 2 years.

The repository there is active, last commit only 2 weeks ago.
It is the local areas themselves that need to maintain the data, so someone must commit a PR there.

**Comment by daniluk4000** [comment]
I will check it
