### ISSUE TITLE
Chicago Approach polygon

### ISSUE THREAD

**Issue by DhruvK1985** [VATSIM-Radar/vatsim-radar#516]
### Your Vatsim CID

878508

### Radar version

0.5.0

### Describe your issue

Chicago Approach (CHI_x_APP) is drawing as a circle:

[https://i.imgur.com/IypR0nr.png](url)

### Reproduction steps

Load site.

### Platform

Any

### Additional info

[](url)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by Adrian2k** [comment]
Checked if its even defined in the tracon dataset?
https://github.com/vatsimnetwork/simaware-tracon-project

**Comment by DhruvK1985** [comment]
All US TRACONs are defined. I noticed the same issue with a handful of other approach controls last night. The common thread seems to be that the callsign of the approach control doesn’t directly correspond with the primary airport ICAO code
