### ISSUE TITLE
A35K icon does not match

### ISSUE THREAD

**Issue by DotWallop** [VATSIM-Radar/vatsim-radar#521]
### Your Vatsim CID

1227980

### Radar version

0.5.0-1

### Describe your issue

Icon for A35K does not match correctly. 

### Reproduction steps

Look at A35K flying on VR
Confirm ICAO code
Match size (preferably with mechanical ruler on monitor), adjust for zoom rate to get accurate conversion for length
Look up length of A35K, confirm it doesn’t match
Have yourself a treat on me (figuratively)

### Platform

Windows

### Additional info

Hi Dani <3

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Hello

**Comment by DotWallop** [comment]
Fix!
