### ISSUE TITLE
Not showing sector overlay on map

### ISSUE THREAD

**Issue by mrkazaam** [VATSIM-Radar/vatsim-radar#536]
### Your Vatsim CID

1120988

### Radar version

 v0.5.0-1

### Describe your issue

I was online at ANK_W_CTR but it wasn't showing on the map
![Screenshot_1](https://github.com/user-attachments/assets/17ab7726-4071-4b21-ba9c-eb0a61f8a6a4)

### Reproduction steps

NIL

### Platform

Windows, Firefox

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Will be fixed on production today I hope

**Comment by mrkazaam** [comment]
thank you!
