### ISSUE TITLE
Colons not showing up in controller bio

### ISSUE THREAD

**Issue by alphagolfcharlie** [VATSIM-Radar/vatsim-radar#539]
### Your Vatsim CID

1826151

### Radar version

0.5.1-1

### Describe your issue

Not sure if this is just vatsim radar or all vatsim (and sorry if it's already been reported! I checked and isn't an 'open issue' - but for some reason colons I put in my controller bio never show up (other controllers are facing the same) eg https://clevelandcenter.org/feedback shows up as https //clevelandcenter.org/feedback which makes pasting links more tricky. Reporting just in case it's not a general vatsim issue. Screenshot provided of a fellow controller's bio. 
<img width="428" alt="Screenshot 2024-12-01 at 23 09 36" src="https://github.com/user-attachments/assets/bfcd38bb-b3e9-4e28-9f8d-f459d275eae0">

### Reproduction steps

Hover over a controller bio including a colon in it. 

### Platform

All (ios, windows, macos, safari on ios and chrome on win/mac) 

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
API bug as I remember
