### ISSUE TITLE
FPS drop on Web version

### ISSUE THREAD

**Issue by bruced39** [VATSIM-Radar/vatsim-radar#545]
### Your Vatsim CID

1257208

### What do you suggest?

I'm noticing (using Firefox) when I am on the tab showing vatsim radar I lose roughly 50% of my FPS. If i click another tab I get my FPS back. Has anyone else had this issue and is this a known issue with a fix?

### Why do you need that?

Make it better using while flying XP12

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Do you have vector mode enabled?

**Comment by bruced39** [comment]
Good Morning,

I do not have vector mode on while using the web version of the program.

David Bruce

**Comment by daniluk4000** [comment]
If you do not have vector mode enabled, you can try to use Chrome-based browser. To improve your experience there, you can install App via About menu and use it as regular app

**Comment by bruced39** [comment]
Thank you for your advice. Can I ask, I went to look into downloading the app to see if that would not affect my frames but I do not see what I need to download from the link to github. Can you provide me a link to download the app and which file I need to download for windows computers?

Thank you. Also, GREAT WORK on this program!!!

David Bruce

**Comment by daniluk4000** [comment]
> Thank you. Also, GREAT WORK on this program!!!

Thanks!

As for installing the app, open any Chromium-based browser, open About menu on VATSIM Radar, and click on Install App

![image](https://github.com/user-attachments/assets/ed580a83-34e6-4523-86dc-7baa05c19967)

Then you can close your browser and continue using VATSIM Radar as standalone app

**Comment by bruced39** [comment]
Hello Danila,

I recently sent you an email with a screen shot showing I do not have an install pap option under about. I can let you know it never shows when logged in with firefox but when I go to Microsoft edge the option to install App is there. Not sure why this happens but wanted you to know.

Also I installed the app but when I click to Connect Vatsim I get an invalid Client, Client authentication error and it never gets to the page where it asked for my vatsim login. This is all via the app. Works fine on the web.

Thank you,
Dave

**Comment by daniluk4000** [comment]
Please re check authorization in Edge

**Comment by bruced39** [comment]
Hello,

An update was made and I restarted the app and it now allows me to log into Vatsim. My issue has been resolved. Thank you.

David Bruce
