### ISSUE TITLE
RPHI Sectors

### ISSUE THREAD

**Issue by HacobAllon** [VATSIM-Radar/vatsim-radar#548]
### Your Vatsim CID

1504338

### What do you suggest?

Hello! I'm one of the facility directors at VATPHIL and I was checking the map, and it unfortunately doesnt have our other sectors of manila control  

### Why do you need that?

When we have multiple sectors open, it only shows that controller controls top down the whole country where in reality it only controls a part.
The sectors are as shown in the image. However MNL_CTR (119.300) controls every sector.
![image](https://github.com/user-attachments/assets/838f307b-af44-4d5b-a1cc-46257b5dd5d1)

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
Heya! This should be updated in VatSpy project

https://github.com/vatsimnetwork/vatspy-data-project

**Comment by HacobAllon** [comment]
Thank you
