### ISSUE TITLE
SBNF Location

### ISSUE THREAD

**Issue by rssraam** [VATSIM-Radar/vatsim-radar#552]
### Your Vatsim CID

1508797

### Radar version

0.5.1-1-final

### Describe your issue

The location of SBNF is wrong in the map:

![sbnf1](https://github.com/user-attachments/assets/bf9a0304-2d6f-4ef6-8f5f-0213ce4e22fa)
![sbnf2](https://github.com/user-attachments/assets/1931525a-cf82-4b14-b3d4-3e6113bc7a95)
![sbnf3](https://github.com/user-attachments/assets/952b3a0c-5ce2-43e2-b08d-a517771db66d)

### Reproduction steps

I landed, checked on map and  according to the map was still "arriving"

### Platform

Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
This has to be fixed in https://github.com/vatsimnetwork/vatspy-data-project
