### ISSUE TITLE
YSSY SY-W_GND Not showing when connected

### ISSUE THREAD

**Issue by planespottermax** [VATSIM-Radar/vatsim-radar#555]
### Your Vatsim CID

1638887

### Radar version

v0.5.1-1-final

### Describe your issue

The SMC position at YSSY, SY-W_GND has replaced the old position, SY-E_GND.

### Reproduction steps

Create a new recognisable position for SY-W_GND 
Note: its a non-standard position. (not primary)

### Platform

Win 11, Chrome

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
VatSpy needs to be updated with new alias

https://github.com/vatsimnetwork/vatspy-data-project

![Uploading image.png…]()

**Comment by planespottermax** [comment]
are u able to manually edit the data you apply to the radar?

**Comment by daniluk4000** [comment]
> are u able to manually edit the data you apply to the radar?

If this is THAT important I can do the hotfix, but I prefer to not do that all the time :D

**Comment by planespottermax** [comment]
Well it HAS been like that for a very long time since that position was in use. I would hope that if you could fix the issue you would decide to do so.

**Comment by daniluk4000** [comment]
> Well it HAS been like that for a very long time since that position was in use. I would hope that if you could fix the issue you would decide to do so.

Okay, let's do it like this. You (or someone local) add PR with a fix - I add a TEMPORAL fix for you in VATSIM Radar, so I can remove it later when VatSpy update is released
