### ISSUE TITLE
Through flights tracking issue

### ISSUE THREAD

**Issue by nopresnik** [VATSIM-Radar/vatsim-radar#556]
### Your Vatsim CID

1239332

### Radar version

v0.5.1-1-final

### Describe your issue

G'day team,

I’ve encountered a bug related to conducting a through flight with the same callsign. Last night, I flew into WADD from YMML as MXD178. Just over 12 hours later, I logged on to complete the second leg of the journey from WADD to WMKK using the same callsign. However, I noticed two issues:
  1. The track from the previous flight flickers every few seconds.
  2. Most critically, the second flight's track is not recorded properly. Instead, it displays a direct line between my aircraft and the departure aerodrome.

I've attached two screenshots that show the flickering state.

![image](https://github.com/user-attachments/assets/bb4f6618-0094-4355-bc0a-df9a3d19763d)
![image](https://github.com/user-attachments/assets/96f759f4-b342-4da2-b0be-1f616e73fd46)

### Reproduction steps

1. File and fly the first leg of a through flight.
2. Disconnect form the network upon arrival.
3. File and fly the second leg of the through flight.

### Platform

Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by nopresnik** [comment]
Maybe the second flight is not being tracked due to another issue??? #557

**Comment by daniluk4000** [comment]
Fixed now

**Comment by Pricelss** [comment]
> Fixed now

May I ask as to what the issue was? Was it something on the host side? from Vatsim?

**Comment by daniluk4000** [comment]
We had server issue on Radar side
