### ISSUE TITLE
Map failure?

### ISSUE THREAD

**Issue by Pricelss** [VATSIM-Radar/vatsim-radar#557]
### Your Vatsim CID

1387149

### Radar version

0.5.1.--final

### Describe your issue

The general map doesnt display previous paths and Departure point is not current. I left OAK about 7 hours ago, dod OAK-SAN and then SAN-HNL, now on HNL-ITO and its coming up with my origin still being OAK? Does it on both Next, and the main public.
![Screenshot 2024-12-14 190909](https://github.com/user-attachments/assets/5476c0a3-1abb-4b10-84e6-fd37f944450a)

### Reproduction steps

Should reproduce by just opening next.vatsim-radar. Not sure how else to show it. 

### Platform

Windows 11 22635.4580 , Chrome 131.0.6778.140

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by daniluk4000** [comment]
Should be fixed now
