### ISSUE TITLE
Not Displaying ATIS info under controller for TXKF BDA

### ISSUE THREAD

**Issue by brianerbis** [VATSIM-Radar/vatsim-radar#560]
### Your Vatsim CID

1409889

### Radar version

v0.5.1-1-final

### Describe your issue

When connected as "BDA_TWR", "atis not available" will be displayed under controller info. 
![d38b8f961fc2c302b220a15f5a2a411f](https://github.com/user-attachments/assets/f4a11a44-61b9-4adb-ba85-9977c915132a)

### Reproduction steps

Connect to a cab position at BDA using CRC.

### Platform

Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
It's most likely this controller did not set ATIS.

You can validate this in your pilot client and VatSpy. If ATIS is present in pilot client but not Radar and VatSpy, this could be an API bug.

**Comment by brianerbis** [comment]
I was the controller on this position and I indeed had an atis posted, which is visible in the screenshot. it is shown as "txkf_atis"

**Comment by daniluk4000** [comment]
> I was the controller on this position and I indeed had an atis posted, which is visible in the screenshot. it is shown as "txkf_atis"

This is not _that_ ATIS, it's your TWR ATIS. Uh... 

![image](https://github.com/user-attachments/assets/0b679a07-e670-4915-90c9-fbc034d1dee7)

Those lines will be my ATIS as TWR. TXKF_ATIS is a separate position and has separate ATIS.

Your ATIS could, for example, be Bermuda Tower or something like it.

**Comment by brianerbis** [comment]
whoops I understand now, thanks for the clarification. Didn't mean to waste your time.

VATSIMRadar is great. thanks for putting your time and skill toward the community.
