### ISSUE TITLE
Center name not showing for all controllers

### ISSUE THREAD

**Issue by GermainDeDuck** [VATSIM-Radar/vatsim-radar#583]
### Your Vatsim CID

1696195

### Radar version

 v1.0.0-alpha.4

### Describe your issue

When displaying VatGlasses radars, the name of most controlzones doesn't show up (you can click on it to show what controller it is though)

![image](https://github.com/user-attachments/assets/93b618ea-4026-41cc-9a3d-33679f18854e)

### Reproduction steps

start VR
turn on Vatglasses Integration
look at online controllers

### Platform

Version 131.0.6778.205 (Official Build) (64-bit)

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned
- [X] I am QA or Patreon member and using next.vatsim-radar.com
- [X] I couldn't reproduce it on production / it's issue in new functionality

**Comment by FX5F** [comment]
It's not a bug, the labels for centers will only be used as fallback for stations which are not in the vatglasses data.
