### ISSUE TITLE
Copenhagen CTR False displayed

### ISSUE THREAD

**Issue by FlyforLive** [VATSIM-Radar/vatsim-radar#585]
### Your Vatsim CID

1667561

### Radar version

 v1.0.0-alpha.4

### Describe your issue

Copenhagen East CTR is displayed incorrectly
![image](https://github.com/user-attachments/assets/441bb62d-8977-4ce8-801a-e86d1d3c4d1a)

### Reproduction steps

I just flew and Vatglasses loaded in. Then the bow was created

### Platform

Windows

### Additional info

I am very confident that with the help of Vatglasses the expirience of Vatsim Radar will increase a lot. I look forward to what the future will bring!

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
VG doesn't have definition for this one sector
