### ISSUE TITLE
Smaller Aircraft Icons/Labels

### ISSUE THREAD

**Issue by glott** [VATSIM-Radar/vatsim-radar#97]
### Your Vatsim CID

redacted

### What do you suggest?

Aircraft icons are currently quite large, especially when compared to other software like Vattastic and SimAware. It would be nice to be able to adjust them in the settings to be a little smaller. 

### Why do you need that?

Having smaller icons/labels would make the map less cluttered, especially during busier times. 

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment]
I will reduce max icon size from 40 to 35 in 0.4.2. For customization - let's add this to confirmed features.

**Comment by glott** [comment]
> I will reduce max icon size from 40 to 35 in 0.4.2. For customization - let's add this to confirmed features.

Is this slated to be a new option in 0.5.0?

**Comment by daniluk4000** [comment]
> > I will reduce max icon size from 40 to 35 in 0.4.2. For customization - let's add this to confirmed features.
> 
> Is this slated to be a new option in 0.5.0? So you can choose to lower it smaller than 35?

Negative, but I'll add "scale" option in 0.5.0

**Comment by glott** [comment]
> Negative, but I'll add "scale" option in 0.5.0

Great. If a user is scaling their icons to be smaller, could the aircraft callsigns be viewed at lower zoom levels (e.g. so you can see callsigns when zooming over the whole Atlantic)
